### PR TITLE
feat: lbac 2102: update template mail candidat

### PR DESCRIPTION
**Pull request by kevbarns**
- https://tableaudebord-apprentissage.atlassian.net/browse/LBA-596

### CODE REVIEW

**Comment by kevbarns** [comment]
🚀

**Review by remy-auricoste — APPROVED** [review]

**Comment by kevbarns** [comment]
🚀

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Review by remy-auricoste — APPROVED** [review]

**Pull request merged**
