### PR TITLE
feat: remove password

### PR DESCRIPTION
**Pull request by kevbarns**
- remove password from code & collection using migration file

Note @moroine : command migration:create does not work. I think it's related to the securisation of the local mongodb.

### CODE REVIEW

**Review by moroine — APPROVED** [review]

**Comment by moroine** [comment]
🚀

**Comment by moroine** [comment]
🚀

**Review by antoinebigard — APPROVED** [review]
Bonne idée

**Review by remy-auricoste — APPROVED** [review]
:rocket:

**Comment by moroine** [comment]
🚀

**Pull request merged**
