### PR TITLE
feat: LBA-481 bouton de partage d'offres

### PR DESCRIPTION
**Pull request by alanlr**
https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353&selectedIssue=LBA-481

### CODE REVIEW

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by guilletmarion** [comment]
🚀

**Comment by kevbarns** [comment]
🚀

**Comment by kevbarns** [comment]
🚀

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by kevbarns** [comment]
🚀

**Comment by alanlr** [comment]
:rocket:

**Review by remy-auricoste — APPROVED** [review]

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Comment by alanlr** [comment]
:rocket:

**Pull request merged**
